
POST http://127.0.0.1:8000/api/project HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|sV26aV5egS88Fs4OZ2yHzpvPJSzqegJRoue5MS95

{
    "leader": "Ibson",
    "team": "CodesWell Team",
    "phone_number": "0800000000888",
    "email": "ibson@demo.com",
    "project_title": "Family Project",
    "project_description": "Hidden"
}

###
GET http://127.0.0.1:8000/api/contact-us HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "name": "Abduljawad Ibrahim",
    "email": "jay@demo.com",
    "subject": "Sample Subject",
    "message": "Sample Message"
}
